// <auto-generated />
using System;
using GoogleApi.DBContext.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoogleApi.DBContext.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220731054349_3")]
    partial class _3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GoogleApi.Domain.Entities.Geoglobal.bounds", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id_northeast")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id_southwest")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Id_northeast")
                        .IsUnique();

                    b.HasIndex("Id_southwest")
                        .IsUnique();

                    b.ToTable("tbl_bounds", (string)null);
                });

            modelBuilder.Entity("GoogleApi.Domain.Entities.Geoglobal.Cordenadas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Longitud")
                        .IsUnicode(true)
                        .HasColumnType("float");

                    b.Property<double>("latitud")
                        .IsUnicode(true)
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("tbl_cordenada", (string)null);
                });

            modelBuilder.Entity("GoogleApi.Domain.Entities.Geoglobal.Cordenadas_location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id_Cordenadas")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Id_Cordenadas")
                        .IsUnique();

                    b.ToTable("tbl_location", (string)null);
                });

            modelBuilder.Entity("GoogleApi.Domain.Entities.Geoglobal.Cordenadas_northeast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id_Cordenadas")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Id_Cordenadas")
                        .IsUnique();

                    b.ToTable("tbl_northeast", (string)null);
                });

            modelBuilder.Entity("GoogleApi.Domain.Entities.Geoglobal.Cordenadas_southwest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id_Cordenadas")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Id_Cordenadas")
                        .IsUnique();

                    b.ToTable("tbl_southwest", (string)null);
                });

            modelBuilder.Entity("GoogleApi.Domain.Entities.Geoglobal.bounds", b =>
                {
                    b.HasOne("GoogleApi.Domain.Entities.Geoglobal.Cordenadas_northeast", "northeast")
                        .WithOne("bounds")
                        .HasForeignKey("GoogleApi.Domain.Entities.Geoglobal.bounds", "Id_northeast")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tbl_bounds_tbl_northeast");

                    b.HasOne("GoogleApi.Domain.Entities.Geoglobal.Cordenadas_southwest", "southwest")
                        .WithOne("bounds")
                        .HasForeignKey("GoogleApi.Domain.Entities.Geoglobal.bounds", "Id_southwest")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tbl_bounds_tbl_southwest");

                    b.Navigation("northeast");

                    b.Navigation("southwest");
                });

            modelBuilder.Entity("GoogleApi.Domain.Entities.Geoglobal.Cordenadas_location", b =>
                {
                    b.HasOne("GoogleApi.Domain.Entities.Geoglobal.Cordenadas", "Cordenadas")
                        .WithOne("Cordenadas_location")
                        .HasForeignKey("GoogleApi.Domain.Entities.Geoglobal.Cordenadas_location", "Id_Cordenadas")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cordenadas");
                });

            modelBuilder.Entity("GoogleApi.Domain.Entities.Geoglobal.Cordenadas_northeast", b =>
                {
                    b.HasOne("GoogleApi.Domain.Entities.Geoglobal.Cordenadas", "Cordenadas")
                        .WithOne("Cordenadas_northeast")
                        .HasForeignKey("GoogleApi.Domain.Entities.Geoglobal.Cordenadas_northeast", "Id_Cordenadas")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cordenadas");
                });

            modelBuilder.Entity("GoogleApi.Domain.Entities.Geoglobal.Cordenadas_southwest", b =>
                {
                    b.HasOne("GoogleApi.Domain.Entities.Geoglobal.Cordenadas", "Cordenadas")
                        .WithOne("Cordenadas_southwest")
                        .HasForeignKey("GoogleApi.Domain.Entities.Geoglobal.Cordenadas_southwest", "Id_Cordenadas")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cordenadas");
                });

            modelBuilder.Entity("GoogleApi.Domain.Entities.Geoglobal.Cordenadas", b =>
                {
                    b.Navigation("Cordenadas_location")
                        .IsRequired();

                    b.Navigation("Cordenadas_northeast")
                        .IsRequired();

                    b.Navigation("Cordenadas_southwest")
                        .IsRequired();
                });

            modelBuilder.Entity("GoogleApi.Domain.Entities.Geoglobal.Cordenadas_northeast", b =>
                {
                    b.Navigation("bounds")
                        .IsRequired();
                });

            modelBuilder.Entity("GoogleApi.Domain.Entities.Geoglobal.Cordenadas_southwest", b =>
                {
                    b.Navigation("bounds")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
